---
- name: Install zabbix_agent
  hosts: zabbix_agent
  become: true
  tasks:
  - name: zabbix-agent
    copy: src=./zabbix-agent-5.0.9-1.el7.x86_64.rpm dest=/root/zabbix-agent-5.0.9-1.el7.x86_64.rpm seuser=system_u
  - name: install zabbix-agent rpm from a local file
    yum:
      name: /root/zabbix-agent-5.0.9-1.el7.x86_64.rpm
      state: present
  - name: replace in sql files
    shell: sed -i 's/127.0.0.1/192.168.0.200/' /etc/zabbix/zabbix_agentd.conf
  - name: Start zabbix-agent
    service: name=zabbix-agent state=started enabled=yes
