---
- name: Install zabbix_agent
  hosts: zabbix_agent
  become: true
  tasks:
  - name: zabbix-agent
    copy: src=./zabbix-agent2-5.0.15-1.el8.x86_64.rpm dest=/root/zabbix-agent2-5.0.15-1.el8.x86_64.rpm seuser=system_u
  - name: install zabbix-agent rpm from a local file
    yum:
      name: /root/zabbix-agent2-5.0.15-1.el8.x86_64.rpm
      state: present
  - name: copy zabbix configuration file
    copy: src=./zabbix_agentd2.conf dest=/etc/zabbix/zabbix_agentd2.conf seuser=system_u
  - name: Start zabbix-agent
    service: name=zabbix-agent state=started enabled=yes
